config/routes.rb
Rails.application.routes.draw do
  resources :shops
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "shops#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/shop.rb
class Shop < ApplicationRecord
  validates :item, presence: true
  validates :item, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: %i[ show edit update destroy ]

  # GET /shops or /shops.json
  def index
    @shops = Shop.all
    @shop = Shop.new
  end

  # GET /shops/1 or /shops/1.json
  def show
  end

  # GET /shops/new
  def new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops or /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.turbo_stream
        # format.html { redirect_to shops_url, notice: "Item was added." }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@shop)}_form", partial: "form", locals: { shop: @shop })}
        # format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1 or /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to shop_url(@shop), notice: "Shop was successfully updated." }
        # format.json { render :show, status: :ok, location: @shop }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@shop)}") }
        # format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1 or /shops/1.json
  def destroy
    @shop.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@shop)}_item") }
      # format.html { redirect_to shops_url, notice: "Shop was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_params
      params.require(:shop).permit(:item)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingListRails7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container mx-auto">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shops/_errors.html.erb
<% if @shop.errors.any? %>
        <div class="alert alert-danger">
         <!-- <h2><%#= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2> -->

          <ul>
            <% @shop.errors.each do |error| %>
              <li class="list-unstyled"><%= error.full_message %></li>
              <a href="#" class="close" data-dismiss="alert">&#215;</a>
            <% end %>
          </ul>
        </div>
      <% end %>

app/views/shops/_form.html.erb
<div class="row">
  <div class="col">
    <%= form_with(model: shop, id: "#{dom_id(shop)}_form") do |form| %>
      <%= render "shops/errors" %>

      <div class="form-group d-flex">
      <div>
        <%#= form.label :item, style: "display: block" %>
        <%= form.text_field :item, class: "form-control", placeholder: "Add item" %>
      </div>


      <div>
        <%= form.submit class: "btn btn-success" %>
      </div>
      </div>
    <% end %>

  </div>
</div>

app/views/shops/_shop.html.erb
<div id="<%= "#{dom_id(shop)}_item" %>">
  <p>
    <!-- <strong>Title:</strong> -->
    <div class="card card-body">
      <div class="d-flex flex-row">
        <%= turbo_frame_tag dom_id(shop) do %>
          <span class="p-1 h5"><%= shop.item %></span>
          <span class="p-1"><%= link_to "Edit", edit_shop_path(shop), class: "btn btn-warning btn-sm" %></span>
          <span class="float float-right"><%= link_to "Delete", shop_path(shop), data: { turbo_method: :delete }, class: "btn btn-danger btn-sm" %></span> 
        <% end %>
      </div>
    </div> 
  </p>
</div>

app/views/shops/create.turbo_stream.erb
<%= turbo_stream.prepend "shops" do %>
  <%= render "shop", shop: @shop %>
<% end %>

<%= turbo_stream.replace "#{dom_id(Shop.new)}_form" do %>
  <%= render "form", shop: Shop.new %>
<% end %>

app/views/shops/edit.html.erb
<%= turbo_frame_tag dom_id(@shop) do %>
  <%= render "form", shop: @shop %>
<% end %>

app/views/shops/index.html.erb
<div class="row">
  <p style="color: green"><%= notice %></p>
  <div class="mx-auto">
    <h1>Shopping List</h1>
    <%= render 'form', shop: Shop.new %>
    <div id="shops">
      <%= render @shops %>
    </div>
  </div>
</div>

app/views/shops/new.html.erb
<h1>New shop</h1>

<%= render "form", shop: @shop %>

<br>

<div>
  <%= link_to "Back to shops", shops_path %>
</div>

app/views/shops/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @shop %>

<div>
  <%= link_to "Edit this shop", edit_shop_path(@shop) %> |
  <%= link_to "Back to shops", shops_path %>

  <%= button_to "Destroy this shop", @shop, method: :delete %>
</div>